### ISSUE TITLE
Add user routes to the `except` list in VerifyCsrfToken middleware

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudveiltech/CitadelManager#10]
Have to add the user specific routes to the CSRF exception list.

**Comment by dkwiebe** [comment]
I thought that was taken care of by not applying the 'web' settings to the
routes.

Darren Wiebe



T. 877-702-2900
C. 306-830-1349
E. darren@aleph-com.net
w. www.aleph-com.net

Time-honored Values, Modern Technology

**Comment by TechnikEmpire** [comment]
@dkwiebe I thought so too, but I was given the exception. According to some random person on the internet, the protection is applied by default to every single route in 5.4 or something. You have to explicitly disable it apparently and what I saw (exception) seems to support this statement.

**Comment by dkwiebe** [comment]
@TechnikEmpire Aww, that's too bad.

**Comment by dkwiebe** [comment]
I can take care of this tonight if you wish.

**Comment by TechnikEmpire** [comment]
Hey I've got this fixed already I'll merge my changes tonight.

**Comment by TechnikEmpire** [comment]
I'm testing and fixing stuff locally just got a bit carried away. Will try
to stick to the small commits :)

**Comment by TechnikEmpire** [comment]
Fixed in bc7f3a5
