### ISSUE TITLE
When disabling or deleting a user, do we need to manually revoke access tokens?

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudveiltech/CitadelManager#13]
Now that we're using long-lived tokens for our user API, the question of whether we need to revoke all tokens for a user when we delete an account comes up.

While it's unknown whether or not we need to do this when a user is deleted, we almost surely have to do this when a user's account is manually disabled.

**Comment by dkwiebe** [comment]
@TechnikEmpire I think we should just revoke all their tokens when it's disabled.  They can sign in again if we have to kill their account.
