### ISSUE TITLE
Failure to send mail for deactivation requests kills the entire call

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudveiltech/CitadelManager#14]
Recommend isolating the mail subsystem calls when deactivation requests are modified by the administrator and requested by the user.  If mailing fails (like in a local sandbox) then the action partially fails. Admin will get an error when editing the record, and the user will get an error when trying to consume a granted deactivation request, but the granted request will be treated as consumed by the user and deleted. So,

- Admin gets in error state but record will look good.
- User requests deactivation again, record is consumed on server.
- User gets stuck not being permitted to deactivate because the HTTP response was an error response.

I haven't looked at the code but hopefully the mail calls can just be wrapped in a try/catch that gets logged.

**Comment by dkwiebe** [comment]
I can deal with that on Tuesday.
