### ISSUE TITLE
Lists disappearing after uploads

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#16]
The filter lists are missing from Home Default East for the second time in several days. Any idea on what is going on with that?

**Comment by dkwiebe** [comment]
@montesound I'm a little suspicious this might have been caused by php timeouts.  I adjusted the maximum time that a script can run.  Can you let me know if you run into this again?

**Comment by montesound** [comment]
Uploading lists now includes all categories. This seems to be an improvement.

**Comment by dkwiebe** [comment]
Okay, cool. We'll leave this open for a bit and then close it if it's working.  I want to make sure this is working before we integrate automatic list uploads.

**Comment by dkwiebe** [comment]
This has seemed to be working the last while.
