### ISSUE TITLE
Global Application Whitelist and Blacklist

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#18]
_From @montesound on September 8, 2017 13:38_

Add a global application whitelist and blacklist that applies to all groups. This will make it simpler to bypass traffic from known safe apps to all groups.

_Copied from original issue: cloudveiltech/Citadel-Windows#55_

**Comment by dkwiebe** [comment]
@montesound This data is stored in json in groups.app_cfg in the database.  We can certainly alter this but it's going to involve some refactoring in the database.

**Comment by dkwiebe** [comment]
_From @TechnikEmpire on September 11, 2017 1:59_

Might be easier to just implement a copy or merge functionality on this. Something where you just select another group and click "copy settings" and it'll merge in (not overwrite) whatever comes from the selected group.

**Comment by dkwiebe** [comment]
_From @TechnikEmpire on September 11, 2017 1:59_

Having a global system will require probably more work.

**Comment by dkwiebe** [comment]
_From @montesound on September 11, 2017 14:11_

Could we "merge all groups"? That would be fine for me. We could end up with 50 plus groups over time and even more once we build in our business level admin.

**Comment by bluesven869** [comment]
Hi, Darren.
DB schema is changed a little bit.
Do you run the command "php artisan migrate:refresh --seed"?

and then , Please check it.

**Comment by dkwiebe** [comment]
Closing as this is being reimplemented in #63
