### ISSUE TITLE
Add the ability to clone or copy groups on the server.

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/CitadelManager#22]

**Comment by bluesven869** [comment]
![step-1](https://user-images.githubusercontent.com/23646985/32120064-9c1d2072-bb2d-11e7-8fec-c761719a5014.png)
![step-2](https://user-images.githubusercontent.com/23646985/32120085-b26e3f5a-bb2d-11e7-9291-cbc86b01d08d.png)
![step-3](https://user-images.githubusercontent.com/23646985/32120095-ba58f688-bb2d-11e7-9378-6c4ee4c1c0ad.png)

**Comment by dkwiebe** [comment]
@bluesven869 When you were testing this was it saving the filtering rules?  I can copy groups but the filter rules aren't coming across.

**Comment by bluesven869** [comment]
@dkwiebe , I didnot test to copy filtering rules. This is my fault.

**Comment by dkwiebe** [comment]
Can you work on that when you're done the project you're currently working on?

**Comment by bluesven869** [comment]
Yes,

Which is the better?
1. will work after done of native project
2. will work now.

It will take 3~6 hours.

**Comment by dkwiebe** [comment]
@bluesven869 This can wait until the native project is done.

**Comment by bluesven869** [comment]
![screenshot from 2017-11-22 14 29 48](https://user-images.githubusercontent.com/23646985/33141361-b0cda154-cf91-11e7-995b-af796788955a.png)

**Comment by dkwiebe** [comment]
@bluesven869 This looks good.  Thanks.

**Comment by dkwiebe** [comment]
@montesound In my testing this is looking good now.
