### ISSUE TITLE
Admin Site - List of users should be sorted somehow

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#23]
When the ui returns a list of users they should be sorted somehow.

**Comment by dkwiebe** [comment]
@TechnikEmpire I've altered the user model to support returning data like this.  I think the datatable in the admin ui is still ordering by ID.  Can you change that when you're working on the admin ui?

**Comment by TechnikEmpire** [comment]
You can do this simply using the data tables in the GUI. In fact you can order by multiple columns too and make the state persist across sessions. Is that what you're after, sorting in the UI?

**Comment by dkwiebe** [comment]
@TechnikEmpire Datatables seems to be sorting them already as it's not displaying in the order that the webservice returns them.  I can look into this more and will assign it back to myself.

**Comment by TechnikEmpire** [comment]
This can be done in JS/TS. See here:

https://datatables.net/examples/basic_init/table_sorting.html

**Comment by TechnikEmpire** [comment]
If you'd like me to sort it a particular way let me know and I'll just do it in JS.

**Comment by dkwiebe** [comment]
I should be able to figure out myself.  That would be a good exercise.

**Comment by montesound** [comment]
I can see a search field being useful down the road when we have thousands of users and possibly hundreds of groups.

**Comment by dkwiebe** [comment]
@montesound We have that already in the upper right hand of the page.

**Comment by montesound** [comment]
Duh, I overlooked that. Sorry.

**Comment by dkwiebe** [comment]
@montesound I think we can scratch this unless you feel otherwise.  The table save state with the browser so it will always remember how you want it sorted.
