### ISSUE TITLE
Deactivation Request Emails

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/CitadelManager#24]
Can we cc these to our support address for the time being?

For some reason I never get an email when I request a deactivation. Is anyone else?

**Comment by dkwiebe** [comment]
Just a couple more notes based on our Trello page on this.

1. Those emails need to go to accountability partners when they go out.  This requires a tie-in with our AP system.

2. Emails need to get sent out both on deactivation requests and deactivation approvals.

**Comment by dkwiebe** [comment]
@montesound I'm getting those emails myself.  Are you still not getting them?

**Comment by dkwiebe** [comment]
@montesound Could you try another one for me sometime?

**Comment by dkwiebe** [comment]
This has been implemented and tested.
