### ISSUE TITLE
Help text in rule selection view is super small

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudveiltech/CitadelManager#26]
I made some changes to the master CSS file that made the text super small. Example text is:

`Filtering rules. These match specific request strings.` etc etc

**Comment by dkwiebe** [comment]
This is what he's referencing.  Can you improve that?

![image](https://user-images.githubusercontent.com/1034679/32130267-bc0276a6-bb52-11e7-9e42-8dde682d8d21.png)

**Comment by TechnikEmpire** [comment]
Iirc this is all in the main app.css or whatever

**Comment by bluesven869** [comment]
![screenshot from 2017-10-31 14 55 52](https://user-images.githubusercontent.com/23646985/32240287-bc07a2ba-be4b-11e7-9431-e35f0c82e065.png)
