### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/CitadelManager#28]
Not sure where this should be filed but one of my devices (T460s) isn't showing up in the list of licensed devices.

**Comment by df8Ojw** [comment]
Darren, using Amos' email address the Citadel/api only lists 3 devices for him and so I logging in to https://manage.cloudveil.org/citadel/admin which also only shows him with 3 licenses-used. But he has 4 devices activated.

**Comment by dkwiebe** [comment]
@montesound and @df8Ojw, AMOS-T460S is activated under user id 1 which is technikempire.

**Comment by montesound** [comment]
@dkwiebe That is odd. If you take a look under the deactivation requests, it's under my username.

**Comment by dkwiebe** [comment]
@montesound I see that.  That is certainly not expected.  Do you think you might have logged in on here as multiple users?  I'm wondering if something in the local computer got confused or if there's a logic problem in our handing of unblock requests and how we authenticate the device.

**Comment by montesound** [comment]
I don't think I ever logged in as technikempire but it's possible I'm forgetting something.

**Comment by dkwiebe** [comment]
@montesound have you tried purging and reinstalling?

**Comment by dkwiebe** [comment]
@montesound Is this still an issue for you?
