### ISSUE TITLE
Xref Tokens with Activations

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#29]
We should record which token is used with which activation.  If we do that makes it easier to audit them and also it lets us deactivate an installation and the associated token from within the web console when we get that in place.

**Comment by dkwiebe** [comment]
@bluesven869 Does this request make sense to you?

This needs to be done before the comment here(https://github.com/cloudveiltech/CitadelManager/issues/21#issuecomment-340110717) can be completed.

**Comment by bluesven869** [comment]
Hi, @dkwiebe, please check my idea of this work-flow.
1. when the administrator create new users, the activation email has been sent to {user_email"}
2. the user can click the activation link in his mail-in-box. in this moment, (is calling back-end api), the data of {"user_id", "identifier","ip_address", token} will be generated and be save their tables.

Is that right?
Thanks

**Comment by dkwiebe** [comment]
@bluesven869 The app_user_activations table is populated whenever the Windows app is installed on a new computer.  That creates a new activation for that user.

I believe that's controlled here:

Route::middleware(['auth.basic.once','role:admin|user'])->post('/v2/user/gettoken', 'UserController@getUserToken');

**Comment by bluesven869** [comment]
@dkwiebe, thanks for your kindly answer.

**Comment by dkwiebe** [comment]
@bluesven869 the changes you made will go revoke all tokens belonging to that user.
