### ISSUE TITLE
Add ability to delete installations and/or their token

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#32]
Each activation in the database in the database will have a token associated with it once #29 has been completed.  Once that's in place the grid showing activations needs 2 buttons.

1 - Delete.  This just removes the activation.  
2 - Block.  This removes the activation and disables the token so the user will need to sign in again.

@montesound Do you remember why this was on our list?  I have it on my list but I can't remember why.  Does anybody remember?

**Comment by bluesven869** [comment]
![screenshot from 2017-10-31 13 15 32](https://user-images.githubusercontent.com/23646985/32235870-6695769c-be3f-11e7-8134-2528cee49ec5.png)

**Comment by dkwiebe** [comment]
I need to do some refactoring on this one as it would currently delete all tokens belonging to that user.
