### ISSUE TITLE
Add support to manage relaxed policies per installation

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#33]
@TechnikEmpire I'm tagging you on this so you get a notification.  Your thoughts are welcomed.

Citadel includes support to have specific categories of blocks bypassable.  For example, maybe we allow a user to access Youtube for 15 minutes 3 times a day.  That is set in the group configuration

Bypasses Allowed Per Day: 3
Bypass Period (Minutes): 15

![image](https://user-images.githubusercontent.com/1034679/32130108-14e7ec64-bb4f-11e7-872d-657e3784625a.png)

We want to be able to manage this per device.  That will require adding the following fields to the activations table:

bypass_quantity, integer, nullable.  If it's a null  then the group policy applies.  Otherwise the number applies.
bypass_period, integer, nullable.   If it's a null  then the group policy applies.  Otherwise the number applies.  This number is minutes.
bypass_used, integer, default 0.  Bypasses used since last reset.  

As part of this we need a cron job in laravel which sets bypass_used to 0 at X hours.  @montesound if we do this the simple way then we'd reset them globally at one time.  Is this acceptable?

This requires an API endpoint that accepts credentials to identify and authenticate activations.  It will return valid json to the app.  I'd do something like this.

{
  allowed: true,
  message: "Request granted.  Used 3 out of 5."
}

or

{
  allowed: false,
  message: "Request denied.  You have already used 5 out of 5."
}

It should also trigger a Laravel Event (bypass_granted) or (bypass_denied) which we can build listeners for.

**Comment by bluesven869** [comment]
- One question for this issue.
How can the admin change bypass_quantity, bypass_period, bypass_used fields in app_user_activations table?

I mean, which UI is used to change those values?

**Comment by dkwiebe** [comment]
@bluesven869 The admin can't change bypass_used as we'll need to build an api to change that.

Can you build a UI to allow changing bypass_quantity and bypass_period?

**Comment by bluesven869** [comment]
Sure, I can create a UI for this.

**Comment by bluesven869** [comment]
![screenshot from 2017-11-02 22 21 57](https://user-images.githubusercontent.com/23646985/32357546-678bc25c-c01c-11e7-9411-bf7dd129c3d3.png)

![screenshot from 2017-11-02 22 21 53](https://user-images.githubusercontent.com/23646985/32357540-61af7edc-c01c-11e7-980d-8ae029acb665.png)

![screenshot from 2017-11-02 22 21 46](https://user-images.githubusercontent.com/23646985/32357531-58863e2c-c01c-11e7-8be2-15c6cf3910fb.png)
![screenshot from 2017-11-02 22 21 39](https://user-images.githubusercontent.com/23646985/32357526-51ec2b8a-c01c-11e7-8535-e5868751337e.png)

**Comment by kfreezen** [comment]
Testing on production server, issuing commands to /me/bypass does not increment relaxed policy counter.

This might be a duplicate of another comment, but I can't find the other one ATM.

**Comment by dkwiebe** [comment]
@kfreezen This is covered here:  https://github.com/cloudveiltech/CitadelManager/issues/65  Closing this ticket as it only covers the ui implementation.
