### ISSUE TITLE
Add customer_id to users table

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#37]
In many cases the Citadel users will be managed from a billing system.  For those situations we need an identifier to cross reference with a shopping cart or billing system.  
1) This should be an integer, nullable, and unique.
2) We need to be able to populate it from the existing user management API.    
3) We need to be able to see it from the user management system but do not need to be able to edit it.  In fact it would be preferable to not be able to edit it from the web interface.

**Comment by dkwiebe** [comment]
@bluesven869 This is a high priority request which would be nice to get done soon.

**Comment by dkwiebe** [comment]
We have an api in citadel manager to search for users.  We can currently search by email address.  We need to be able to search by customer_id as well.

**Comment by bluesven869** [comment]
![screenshot from 2017-10-30 16 38 14](https://user-images.githubusercontent.com/23646985/32192056-d22a1cc2-bd91-11e7-9dac-d9ede45d262d.png)

**Comment by dkwiebe** [comment]
@df8Ojw This has been added on the testing system.  We'll get it rolled into production soon.

GET https://----.--------------.----/citadel/api/manage/users?customer_id=10
