### ISSUE TITLE
Laravel returning 401 when unable to communicate with database.

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#40]
We're using Laravel and Passport to authenticate the api.  We took the database offline and it was returning 401 messages when users attempted to access the API.  It should be returning preferably a 500 or else maybe a 403 in this case.    This needs investigation as to whether we should be opening a ticket with Laravel on this or just overriding it locally.  The Citadel ticket is here:  https://github.com/cloudveiltech/Citadel-Windows/issues/87

**Comment by bluesven869** [comment]
- ***if db server is down.***
![screenshot from 2017-11-03 12 39 52](https://user-images.githubusercontent.com/23646985/32382650-937c4dd2-c094-11e7-9b33-bfd03cab0df9.png)

- *** if db server is live & user is not authenticated***
![screenshot from 2017-11-03 12 41 52](https://user-images.githubusercontent.com/23646985/32382687-aaac6500-c094-11e7-9e6f-6e2051aea6a6.png)

- *** if db is live & user is authenticated ***
![screenshot from 2017-11-03 12 41 35](https://user-images.githubusercontent.com/23646985/32382711-ba6f1fc8-c094-11e7-858d-32a8d8ef2cf4.png)
