### ISSUE TITLE
Add functionality to push app updates to individual groups

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/CitadelManager#5]

**Comment by TechnikEmpire** [comment]
Implemented in ef5966b

**Comment by TechnikEmpire** [comment]
Well, to a degree. There's three, hardcoded update channels. You could make a model on the server side and use blade to `foreach` over them and dynamically generate the channel options. That would let you create as many channels as you want rather easily.

**Comment by montesound** [comment]
I can't change the Update Channel in the group. It always reverts back to Stable.
Also, it's trying to update even with the channel set to Stable.

**Comment by dkwiebe** [comment]
Resolved in https://github.com/cloudveiltech/CitadelManager/commit/f04671f4eaab5807ae59bd7a58af06a3285d4525
