### ISSUE TITLE
Store software version in database per activation

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#56]
As per ticket (https://github.com/cloudveiltech/Citadel-Windows/issues/116) when the software synchronizes it should store the version number in the database.  This would be exposed under "App User Activations".

**Comment by dkwiebe** [comment]
This data will be sent as part of the sync that happens every few minutes where it checks for updated data.

**Comment by dkwiebe** [comment]
@bluesven869 Did you update the API so this data would be stored?  I don't see it added to the database table.

**Comment by bluesven869** [comment]
@dkwiebe you can see "app_version" field in "app_user_activations" table.
