### ISSUE TITLE
Reword "Delete Activations" Button

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#57]
On the "App User Activations" button the "Delete Activations" button should be changed to say "Retire Activations"

**Comment by bluesven869** [comment]
Fixed.

**Comment by bluesven869** [comment]
@dkwiebe ,
is there anything in this issue?

I think it's already fixed, please let me know your opinion regarding this issue.
Thank you.

**Comment by dkwiebe** [comment]
I think you got it fixed.
