### ISSUE TITLE
Add Passport Token Authentication

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#6]
We are going to be moving the app authentication to use long lived tokens rather than confirming we're logged in on each sync.  This will be done implementing Laravel Passport for the routes used by the app.

**Comment by dkwiebe** [comment]
This is taking me longer than planned.

**Comment by dkwiebe** [comment]
@TechnikEmpire Are you good with the token issued to the desktop app being revoked upon a successful deactivation?

**Comment by dkwiebe** [comment]
@TechnikEmpire this is taken care of in https://github.com/cloudveiltech/CitadelManager/commit/ab1bc1ddeb3f3898c004507d0500610f9e26c641

**Comment by TechnikEmpire** [comment]
@dkwiebe Yeah. I'm assuming it'll just return `401 Unauthorized` if the token is rejected? Also I've been thinking the server side changes over quite a bit so if you're not too deep into this, I can look at it.

**Comment by dkwiebe** [comment]
@TechnikEmpire Good timing, I just committed and pushed Passport token authentication.  There's probably improvements needed but it should work.

As long as the Accept header is set to "application/json" it will return a 401 code.

**Comment by TechnikEmpire** [comment]
@dkwiebe Okay great, thanks. I've been studying the passport system and have some non-critical questions but I'll dig into this first and get "hands on" then come back. Thanks again.

**Comment by dkwiebe** [comment]
@TechnikEmpire This is live on our production system in case you want to start testing against it.

**Comment by TechnikEmpire** [comment]
I'm going to set up a LAN server here and make it so I can auth with license count enforcement without going through the existing auth route. That can remain for the admins to log in, I'm not concerned about security with this new system for users given a) token is a manually set header, not a cookie and b) user route isolation, so I think this is fine to have a separate auth route for users that uses basic auth over HTTPS. This way we can scrap the CSRF complexity too. Basically, everything you suggested all along ;)

**Comment by dkwiebe** [comment]
@TechnikEmpire Ok, then I'll leave that with you.  I took a look at starting it last night but there wasn't time.   I'll keep an eye on any other issues created.

**Comment by TechnikEmpire** [comment]
@dkwiebe I modified the gettoken to be a POST route. Did you need it as GET? By modifying this to POST, disabling CSRF on user routes, copy and pasting the tryActivateAppUser code from AuthenticatesLicensedUsers, this new api is function well.

**Comment by dkwiebe** [comment]
@TechnikEmpire Perfect.  No, I definitely did not need it to be a GET.  Excellent, I hope it wasn't too much more work than doing it yourself would have been.

**Comment by TechnikEmpire** [comment]
@dkwiebe It wasn't too bad, it took longer to get everything set up than these changes did. I was AFK for some time today (shouldn't have said shortly in my comment from earlier in the day!). Anyway I'm going to resume changes in the client, I tested these api changes with a console application.

**Comment by TechnikEmpire** [comment]
I'd call this fixed in bc7f3a5
