### ISSUE TITLE
Expose app version to admin

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/CitadelManager#64]
When viewing activations both under users and the activations page we should show the app_version.

**Comment by bluesven869** [comment]
![screenshot from 2017-12-25 18 55 19](https://user-images.githubusercontent.com/23646985/34343183-69c3756c-e9a5-11e7-989d-fa7468e697dd.png)

**Comment by dkwiebe** [comment]
@bluesven869 Can you add that on this page as well:
![image](https://user-images.githubusercontent.com/1034679/34428713-dda3be1a-ec0c-11e7-85cd-841519323518.png)

**Comment by bluesven869** [comment]
![screenshot from 2018-01-02 22 12 12](https://user-images.githubusercontent.com/23646985/34506269-0a06f00c-f00a-11e7-97bf-33d08983a8d8.png)

**Comment by bluesven869** [comment]
Done

**Comment by bluesven869** [comment]
![screenshot from 2018-01-02 22 23 50](https://user-images.githubusercontent.com/23646985/34506460-a663049e-f00b-11e7-8747-c5dbec9645c2.png)
