### ISSUE TITLE
New libs lock us in at requiring php >= 7.1

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudveiltech/CitadelManager#7]
`doctrine/dbal v2.6.1 requires php ^7.1`

Non-issue if you're okay with this. WAMP ships with php 7.0.x.

**Comment by dkwiebe** [comment]
@TechnikEmpire I added that dependency.  I was thinking that would be fine as it's getting much more common.

**Comment by TechnikEmpire** [comment]
@dkwiebe Okay cool no worries I'll close this out. I'll just configure a network server on nix here for dev.

**Comment by dkwiebe** [comment]
@TechnikEmpire  That library is needed for migrations to work with database tables.

**Comment by TechnikEmpire** [comment]
oh boy okay I thought it was a dep of the logger. Woopsies. Must just be oddities from composer lock/json synchronization.

**Comment by dkwiebe** [comment]
I added a SQL logger too.  By default I believe it's turned off but you can turn it on in your .env file.  I find that very useful for troubleshooting to see exactly what is going on.
