### ISSUE TITLE
Need to modify the installer to run oauth migrations/setup?

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudveiltech/CitadelManager#9]
The built in installer doesn't appear to take care of running laravel passport migrations. I had to manually run:

`php artisan migrate`

`php artisan passport:install`

The first to set up oauth tables, and the second to generate oauth keys. Should be handled by the installer? Or just update wiki installation instructions?

**Comment by dkwiebe** [comment]
I'd suggest just updating the wiki as I think this is going to be necessary
for future updates.

Darren Wiebe



T. 877-702-2900
C. 306-830-1349
E. darren@aleph-com.net
w. www.aleph-com.net

Time-honored Values, Modern Technology
